// AUTO-GENERATED from world-countries (independent / UN members + TW, PS).
// A compact list for the registration "Country & city" form field so the client
// bundle does not pull in the full world-countries dataset. Regenerate with the
// node snippet in the commit that introduced this file if the source list changes.

export type CountryOption = { f: string; n: string }; // flag emoji, English common name

export const COUNTRY_OPTIONS: CountryOption[] = [
  { f: "🇦🇫", n: "Afghanistan" },
  { f: "🇦🇱", n: "Albania" },
  { f: "🇩🇿", n: "Algeria" },
  { f: "🇦🇩", n: "Andorra" },
  { f: "🇦🇴", n: "Angola" },
  { f: "🇦🇬", n: "Antigua and Barbuda" },
  { f: "🇦🇷", n: "Argentina" },
  { f: "🇦🇲", n: "Armenia" },
  { f: "🇦🇺", n: "Australia" },
  { f: "🇦🇹", n: "Austria" },
  { f: "🇦🇿", n: "Azerbaijan" },
  { f: "🇧🇸", n: "Bahamas" },
  { f: "🇧🇭", n: "Bahrain" },
  { f: "🇧🇩", n: "Bangladesh" },
  { f: "🇧🇧", n: "Barbados" },
  { f: "🇧🇾", n: "Belarus" },
  { f: "🇧🇪", n: "Belgium" },
  { f: "🇧🇿", n: "Belize" },
  { f: "🇧🇯", n: "Benin" },
  { f: "🇧🇹", n: "Bhutan" },
  { f: "🇧🇴", n: "Bolivia" },
  { f: "🇧🇦", n: "Bosnia and Herzegovina" },
  { f: "🇧🇼", n: "Botswana" },
  { f: "🇧🇷", n: "Brazil" },
  { f: "🇧🇳", n: "Brunei" },
  { f: "🇧🇬", n: "Bulgaria" },
  { f: "🇧🇫", n: "Burkina Faso" },
  { f: "🇧🇮", n: "Burundi" },
  { f: "🇰🇭", n: "Cambodia" },
  { f: "🇨🇲", n: "Cameroon" },
  { f: "🇨🇦", n: "Canada" },
  { f: "🇨🇻", n: "Cape Verde" },
  { f: "🇨🇫", n: "Central African Republic" },
  { f: "🇹🇩", n: "Chad" },
  { f: "🇨🇱", n: "Chile" },
  { f: "🇨🇳", n: "China" },
  { f: "🇨🇴", n: "Colombia" },
  { f: "🇰🇲", n: "Comoros" },
  { f: "🇨🇷", n: "Costa Rica" },
  { f: "🇭🇷", n: "Croatia" },
  { f: "🇨🇺", n: "Cuba" },
  { f: "🇨🇾", n: "Cyprus" },
  { f: "🇨🇿", n: "Czechia" },
  { f: "🇩🇰", n: "Denmark" },
  { f: "🇩🇯", n: "Djibouti" },
  { f: "🇩🇲", n: "Dominica" },
  { f: "🇩🇴", n: "Dominican Republic" },
  { f: "🇨🇩", n: "DR Congo" },
  { f: "🇪🇨", n: "Ecuador" },
  { f: "🇪🇬", n: "Egypt" },
  { f: "🇸🇻", n: "El Salvador" },
  { f: "🇬🇶", n: "Equatorial Guinea" },
  { f: "🇪🇷", n: "Eritrea" },
  { f: "🇪🇪", n: "Estonia" },
  { f: "🇸🇿", n: "Eswatini" },
  { f: "🇪🇹", n: "Ethiopia" },
  { f: "🇫🇯", n: "Fiji" },
  { f: "🇫🇮", n: "Finland" },
  { f: "🇫🇷", n: "France" },
  { f: "🇬🇦", n: "Gabon" },
  { f: "🇬🇲", n: "Gambia" },
  { f: "🇬🇪", n: "Georgia" },
  { f: "🇩🇪", n: "Germany" },
  { f: "🇬🇭", n: "Ghana" },
  { f: "🇬🇷", n: "Greece" },
  { f: "🇬🇩", n: "Grenada" },
  { f: "🇬🇹", n: "Guatemala" },
  { f: "🇬🇳", n: "Guinea" },
  { f: "🇬🇼", n: "Guinea-Bissau" },
  { f: "🇬🇾", n: "Guyana" },
  { f: "🇭🇹", n: "Haiti" },
  { f: "🇭🇳", n: "Honduras" },
  { f: "🇭🇺", n: "Hungary" },
  { f: "🇮🇸", n: "Iceland" },
  { f: "🇮🇳", n: "India" },
  { f: "🇮🇩", n: "Indonesia" },
  { f: "🇮🇷", n: "Iran" },
  { f: "🇮🇶", n: "Iraq" },
  { f: "🇮🇪", n: "Ireland" },
  { f: "🇮🇱", n: "Israel" },
  { f: "🇮🇹", n: "Italy" },
  { f: "🇨🇮", n: "Ivory Coast" },
  { f: "🇯🇲", n: "Jamaica" },
  { f: "🇯🇵", n: "Japan" },
  { f: "🇯🇴", n: "Jordan" },
  { f: "🇰🇿", n: "Kazakhstan" },
  { f: "🇰🇪", n: "Kenya" },
  { f: "🇰🇮", n: "Kiribati" },
  { f: "🇰🇼", n: "Kuwait" },
  { f: "🇰🇬", n: "Kyrgyzstan" },
  { f: "🇱🇦", n: "Laos" },
  { f: "🇱🇻", n: "Latvia" },
  { f: "🇱🇧", n: "Lebanon" },
  { f: "🇱🇸", n: "Lesotho" },
  { f: "🇱🇷", n: "Liberia" },
  { f: "🇱🇾", n: "Libya" },
  { f: "🇱🇮", n: "Liechtenstein" },
  { f: "🇱🇹", n: "Lithuania" },
  { f: "🇱🇺", n: "Luxembourg" },
  { f: "🇲🇬", n: "Madagascar" },
  { f: "🇲🇼", n: "Malawi" },
  { f: "🇲🇾", n: "Malaysia" },
  { f: "🇲🇻", n: "Maldives" },
  { f: "🇲🇱", n: "Mali" },
  { f: "🇲🇹", n: "Malta" },
  { f: "🇲🇭", n: "Marshall Islands" },
  { f: "🇲🇷", n: "Mauritania" },
  { f: "🇲🇺", n: "Mauritius" },
  { f: "🇲🇽", n: "Mexico" },
  { f: "🇫🇲", n: "Micronesia" },
  { f: "🇲🇩", n: "Moldova" },
  { f: "🇲🇨", n: "Monaco" },
  { f: "🇲🇳", n: "Mongolia" },
  { f: "🇲🇪", n: "Montenegro" },
  { f: "🇲🇦", n: "Morocco" },
  { f: "🇲🇿", n: "Mozambique" },
  { f: "🇲🇲", n: "Myanmar" },
  { f: "🇳🇦", n: "Namibia" },
  { f: "🇳🇷", n: "Nauru" },
  { f: "🇳🇵", n: "Nepal" },
  { f: "🇳🇱", n: "Netherlands" },
  { f: "🇳🇿", n: "New Zealand" },
  { f: "🇳🇮", n: "Nicaragua" },
  { f: "🇳🇪", n: "Niger" },
  { f: "🇳🇬", n: "Nigeria" },
  { f: "🇰🇵", n: "North Korea" },
  { f: "🇲🇰", n: "North Macedonia" },
  { f: "🇳🇴", n: "Norway" },
  { f: "🇴🇲", n: "Oman" },
  { f: "🇵🇰", n: "Pakistan" },
  { f: "🇵🇼", n: "Palau" },
  { f: "🇵🇸", n: "Palestine" },
  { f: "🇵🇦", n: "Panama" },
  { f: "🇵🇬", n: "Papua New Guinea" },
  { f: "🇵🇾", n: "Paraguay" },
  { f: "🇵🇪", n: "Peru" },
  { f: "🇵🇭", n: "Philippines" },
  { f: "🇵🇱", n: "Poland" },
  { f: "🇵🇹", n: "Portugal" },
  { f: "🇶🇦", n: "Qatar" },
  { f: "🇨🇬", n: "Republic of the Congo" },
  { f: "🇷🇴", n: "Romania" },
  { f: "🇷🇺", n: "Russia" },
  { f: "🇷🇼", n: "Rwanda" },
  { f: "🇰🇳", n: "Saint Kitts and Nevis" },
  { f: "🇱🇨", n: "Saint Lucia" },
  { f: "🇻🇨", n: "Saint Vincent and the Grenadines" },
  { f: "🇼🇸", n: "Samoa" },
  { f: "🇸🇲", n: "San Marino" },
  { f: "🇸🇹", n: "São Tomé and Príncipe" },
  { f: "🇸🇦", n: "Saudi Arabia" },
  { f: "🇸🇳", n: "Senegal" },
  { f: "🇷🇸", n: "Serbia" },
  { f: "🇸🇨", n: "Seychelles" },
  { f: "🇸🇱", n: "Sierra Leone" },
  { f: "🇸🇬", n: "Singapore" },
  { f: "🇸🇰", n: "Slovakia" },
  { f: "🇸🇮", n: "Slovenia" },
  { f: "🇸🇧", n: "Solomon Islands" },
  { f: "🇸🇴", n: "Somalia" },
  { f: "🇿🇦", n: "South Africa" },
  { f: "🇰🇷", n: "South Korea" },
  { f: "🇸🇸", n: "South Sudan" },
  { f: "🇪🇸", n: "Spain" },
  { f: "🇱🇰", n: "Sri Lanka" },
  { f: "🇸🇩", n: "Sudan" },
  { f: "🇸🇷", n: "Suriname" },
  { f: "🇸🇪", n: "Sweden" },
  { f: "🇨🇭", n: "Switzerland" },
  { f: "🇸🇾", n: "Syria" },
  { f: "🇹🇼", n: "Taiwan" },
  { f: "🇹🇯", n: "Tajikistan" },
  { f: "🇹🇿", n: "Tanzania" },
  { f: "🇹🇭", n: "Thailand" },
  { f: "🇹🇱", n: "Timor-Leste" },
  { f: "🇹🇬", n: "Togo" },
  { f: "🇹🇴", n: "Tonga" },
  { f: "🇹🇹", n: "Trinidad and Tobago" },
  { f: "🇹🇳", n: "Tunisia" },
  { f: "🇹🇷", n: "Türkiye" },
  { f: "🇹🇲", n: "Turkmenistan" },
  { f: "🇹🇻", n: "Tuvalu" },
  { f: "🇺🇬", n: "Uganda" },
  { f: "🇺🇦", n: "Ukraine" },
  { f: "🇦🇪", n: "United Arab Emirates" },
  { f: "🇬🇧", n: "United Kingdom" },
  { f: "🇺🇸", n: "United States" },
  { f: "🇺🇾", n: "Uruguay" },
  { f: "🇺🇿", n: "Uzbekistan" },
  { f: "🇻🇺", n: "Vanuatu" },
  { f: "🇻🇦", n: "Vatican City" },
  { f: "🇻🇪", n: "Venezuela" },
  { f: "🇻🇳", n: "Vietnam" },
  { f: "🇾🇪", n: "Yemen" },
  { f: "🇿🇲", n: "Zambia" },
  { f: "🇿🇼", n: "Zimbabwe" },
];
